server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zero?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml

